### ISSUE TITLE
期待 vite 文档中文版

### ISSUE THREAD

**Issue by beetaa** [vitejs/docs-cn#1]
期待 vite 文档中文化并愿为之做点力所能及的贡献。

**Comment by weizhanzhan** [comment]
+1

**Comment by captain883** [comment]
造福英语水平并不那么高的同志们

**Comment by KnowsCount** [comment]
wait... 22 stars already before Evan did anything?

**Comment by lceric** [comment]
Nice

**Comment by suruixin** [comment]
+1

**Comment by HomyeeKing** [comment]
刚看完英文文档 ，  学习到了很多 

希望可以献出一份力量

**Comment by TestGifts** [comment]
坐等中文版

**Comment by Shuo-Mr** [comment]
> wait... 22 stars already before Evan did anything?

Now 35

**Comment by gaolingyi-hadi** [comment]
奈斯

**Comment by xstxhjh** [comment]
emmm...

**Comment by hcfw007** [comment]
如果翻译人员不足我可以帮忙（英语专业毕业，现在做前端）

**Comment by Cyenoch** [comment]
@hcfw007 @gaolingyi-hadi  @TestGifts  @HomyeeKing @beetaa 
文档已经由[ShenQingchuan](https://github.com/ShenQingchuan)翻译好了，等待推送到这个库里， [详见](https://github.com/vitejs/vite/pull/1350)

**Comment by ShenQingchuan** [comment]
预计北京时间2月5日晚完成 Vitepress 项目构建和推送。感谢大家的支持。

**Comment by hcfw007** [comment]
> @hcfw007 @gaolingyi-hadi @TestGifts @HomyeeKing @beetaa
> 文档已经由[ShenQingchuan](https://github.com/ShenQingchuan)翻译好了，等待推送到这个库里， [详见](https://github.com/vitejs/vite/pull/1350)

奥利给

**Comment by lwm98** [comment]
加油+1

**Comment by onsummer** [comment]
建国nb！

不好意思走错片场了

**Comment by Andesome** [comment]
一行代码没有就有76个星星了。

**Comment by ddmy** [comment]
看见`vite docs-cn` 激动了了一下，点进来一看是空的。
期待中文文档！

**Comment by ShenQingchuan** [comment]
仓库内已经有了第一版的代码。感谢大家的关注与支持！
想要参与贡献的同学，请阅读 README.md 的内容与 Wiki 区的指南。

目前 Vite 中文文档还处于积极建设、同步翻译内容的活跃维护状态。
我们需要、也很欢迎有大量的时间可以敏捷应对 Vite 英文文档的前端开发同学！

由于本 issue 是第一个 issue，但：

> issue 区不要用来提问题 / 做无关的事 —— @yyx990803 

所以我将关闭（& 锁定）该 issue 不允许后续讨论，望周知。
