### ISSUE TITLE
中文部分显示乱码

### ISSUE THREAD

**Issue by KnowsCount** [vitejs/docs-cn#10]
## Info

- Safari Version 14.0
- macOS Mojave
- 英文环境

---

在本地 `yarn dev` 的时候出现了这样的问题：

![](https://knowscount-1304485449.cos.ap-shanghai.myqcloud.com/img/Screenshot%202021-02-08%20at%2014.34.53.png)

我笔记本本地是英文环境，可能是这个原因？

**Comment by ShenQingchuan** [comment]
距今为止，Safari 上针对 Vitepress 还有一系列的问题，#8 似乎同这些问题也有某些微妙联系...

Vitepress 相关 issue 参见：
- Vitepress 在 dev 模式下 UTF8 相关问题：https://github.com/vuejs/vitepress/issues/218

**Comment by ShenQingchuan** [comment]
closes from #8 due to similarity.

**Comment by KnowsCount** [comment]
https://github.com/vuejs/vitepress/issues/218#issuecomment-780999845

我发现了什么。

**Comment by ShenQingchuan** [comment]
> [vuejs/vitepress#218 (comment)](https://github.com/vuejs/vitepress/issues/218#issuecomment-780999845)
> 
> 我发现了什么。

😃哈哈哈 NICE !!
