### ISSUE TITLE
vite创建选择vue-ts启动失败

### ISSUE THREAD

**Issue by chenggong0804** [vitejs/docs-cn#101]
![image](https://user-images.githubusercontent.com/54263728/117238782-18236b80-ae60-11eb-82e7-e3286b965d2c.png)

错误用图片完整的截出来了，这个是按照官网创建模板后安装依赖以后直接启动的

**Comment by QC-L** [comment]
看错误，和 vite 无关，建议去查下 access is defined 这个错误，大概率是权限问题。

**Comment by QC-L** [comment]
如果还有问题，再打开 issues，我关掉了哈~
