### ISSUE TITLE
代码块不支持火狐浏览器（已尝试开启无痕并禁用全部插件）

### ISSUE THREAD

**Issue by WangJincheng4869** [vitejs/docs-cn#1061]
### 文档的

- [ ] 翻译缺失
- [ ] 翻译不准确
- [X] 其他问题

### 详细描述

如图所示：在火狐（v131.0.3）中无法选择一行，在微软的 Edge 中可以。

![动画](https://github.com/user-attachments/assets/76343791-9812-4375-9189-fc874e50cf97)

**Comment by thinkasany** [comment]
确实在firefox上有问题，先试试点击复制按钮 或者 从最后一行往前复制吧。 这个问题我去官方仓库也提交一个反馈，本仓库理论上只处理翻译相关的处理。
![image](https://github.com/user-attachments/assets/dd58cd1c-8415-4f15-baff-731d26ff3246)

**Comment by thinkasany** [comment]
中文站点一般只处理翻译相关的问题，你的反馈确实存在，我去主仓库提交了 https://github.com/vitejs/vite/issues/18501，  
你可以先尝试操作快一点不要停留，感觉是被那个代码提示影响的， 或者从后往前复制也会好一点。
![image](https://github.com/user-attachments/assets/1a2de32f-a34d-497a-b7ce-c21561aaf27e)

![20241029103309_rec_](https://github.com/user-attachments/assets/20093921-8053-4481-9b9d-588b9b70a409)

**Comment by thinkasany** [comment]
It seems there's a bug (?) in vitepress-twoslash.  https://github.com/shikijs/shiki/issues/822
