### ISSUE TITLE
 import.meta.globEager not work! 

### ISSUE THREAD

**Issue by edu-live** [vitejs/docs-cn#107]
import { defineConfig } from 'vite'
import svelte from '@sveltejs/vite-plugin-svelte'
const modules = import.meta.globEager('./src/baseCmpts/*.svelte')

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [svelte(), modules],
})

**Comment by KnowsCount** [comment]
please do not post any issue with `vite` here in this repository for this is repository is only concerned with the Chinese `vite` documentation.
