### ISSUE TITLE
> I want to determine which CSS outputs are required by each JS entry.

### ISSUE THREAD

**Issue by Sec32fun32** [vitejs/docs-cn#1096]
> I want to determine which CSS outputs are required by each JS entry.

Which relation of `js file -> css file` is expected in your example code? It would be nice if you can provide a reproduction too.

_Originally posted by @hi-ogawa in https://github.com/vitejs/vite/discussions/18708#discussioncomment-11316754_

**Comment by thinkasany** [comment]
The purpose of this project is to do the synchronization of Chinese translation, what you are looking for should be [vite](https://github.com/vitejs/vite).
