### ISSUE TITLE
网站无法正常访问

### ISSUE THREAD

**Issue by LemonAppleMo** [vitejs/docs-cn#1137]
### 文档的

- [ ] 翻译缺失
- [ ] 翻译不准确
- [X] 其他问题

### 详细描述

<img width="842" alt="image" src="https://github.com/user-attachments/assets/950ea6e4-b2b9-4eac-9848-8ec031c59bf7" />

**Comment by waynzh** [comment]
@LemonAppleMo 可以刷新重试下，当前我这边可以正常访问
<img width="1511" alt="image" src="https://github.com/user-attachments/assets/0995845d-f8ae-4a3a-b137-7adfcf34a492" />

**Comment by hero8080** [comment]
可以了非常赞，网页优美，让人赏心悦目，解决问题迅速



---原始邮件---
发件人: "Wayne ***@***.***&gt;
发送时间: 2024年12月25日(周三) 晚上8:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [vitejs/docs-cn] 网站无法正常访问 (Issue #1137)




 
@LemonAppleMo @hero8080 辛苦刷新重试下，重新触发了一次部署，当前我这边可以正常访问
 image.png (view on web)

**Comment by LemonAppleMo** [comment]
赞赞赞~~~~

**Comment by waynzh** [comment]
感谢反馈 🙏
