### ISSUE TITLE
vite会对node_modules内的库进行检验

### ISSUE THREAD

**Issue by cmdparkour** [vitejs/docs-cn#128]
这是报错信息
[@vue/compiler-sfc] ::v-deep usage as a combinator has been deprecated. Use :deep(<inner-selector>) instead.
按理说，这里面的项不应该做较验的，因为即使校验，我们也没有修改的权限，所以这类提示不应该出现，主要是看着蛋疼

**Comment by wjq990112** [comment]
你好，这个 repo 是 Vite 的中文文档，只有与翻译有关的问题会被处理。
其他关于 Vite 的问题请移步至 [Vite 的主 repo](https://github.com/vitejs/vite)。
