### ISSUE TITLE
[vite] Internal server error: PostCSS plugin vite-url-rewrite requires PostCSS 8. Migration guide for end-users:

### ISSUE THREAD

**Issue by gxc-98** [vitejs/docs-cn#133]
i dont know why[vite] Internal server error: PostCSS plugin vite-url-rewrite requires PostCSS 8.
Migration guide for end-users:

**Comment by wjq990112** [comment]
Hello, this repo is the document of Vite for Chinese, only issues related to translation will be dealt with.
For other questions about vite, please refer to the [main repo of Vite](https://github.com/vitejs/vite).
