### ISSUE TITLE
vite打包之后css文件中引用的静态资源路径不对

### ISSUE THREAD

**Issue by ProjectSean** [vitejs/docs-cn#139]
1. 当我将静态资源（图片，字体）放在src的assets文件下，打包之后，所有css, js以及其他静态文件都会在dist的assets文件下。但是css中引用静态资源的路径却是"./assets/xxxx"，应当为“./xxxx”

2. 当我将静态资源（图片，字体）放在public文件下时，打包之后，css文件在dist的assets文件下，其他静态文件直接存在dist文件下。但是css中引用静态资源的路径却是"./xxxx"，应当为“../xxxx”

**Comment by wjq990112** [comment]
你好，这个 repo 是 Vite 的中文文档，只有与翻译有关的问题会被处理。
其他关于 Vite 的问题请移步至 [Vite 的主 repo](https://github.com/vitejs/vite)。
