### ISSUE TITLE
CDN方式引入资源可用，但在vscode显示红色波浪线

### ISSUE THREAD

**Issue by csdudu** [vitejs/docs-cn#143]
"vite": "^2.1.5"，我在index.html中引入资源：
`<script src="https://cdn.jsdelivr.net/npm/moment@2.29.1/moment.min.js"></script>
<script src="https://cdn.bootcdn.net/ajax/libs/lodash.js/4.17.21/lodash.min.js"></script>`

moment和lodash全局可用，但是显示红色波浪线，很不爽，显然是vscode找不到引用，请问如何处理？
![Image](https://user-images.githubusercontent.com/5706088/121040615-9fa82580-c7e4-11eb-9abb-d855bb3c5a6b.png)

**Comment by KimYangOfCat** [comment]
本仓库仅接受关于中文文档的修正翻译等问题，关于具体使用的问题，建议上 Vue Forum 的中文板块提问，更有助于你的问题解答哦
