### ISSUE TITLE
vite can't run when i import a underfine module

### ISSUE THREAD

**Issue by cmdparkour** [vitejs/docs-cn#156]
1. yarn remove a module
2. yarn run dev
3. this is to show
![image](https://user-images.githubusercontent.com/35911743/122518406-ba2f9980-d043-11eb-8e88-5449f902c140.png)

it's not a bug but i think it's should be working whether or not it's in my node_modules

**Comment by ShenQingchuan** [comment]
It seems that your issue description is not clear enough about what the real problem is ...
I can't figure out what you want...

And in fact, you should create an issue in [Vite official repo](https://github.com/vitejs/vite/issues), no more issues at docs repo, please.
