### ISSUE TITLE
Should we specify a term translation convention?

### ISSUE THREAD

**Issue by Ardor-Zhang** [vitejs/docs-cn#163]
In the process of translation or proofreading, I found that there are many translated versions of a word，for instance,
"bundle": "打包，构建，捆绑，编译".  So, I suggest we should specify a term translation convention, like [vuejs 术语翻译约定](https://github.com/vuejs/docs-next-zh-cn/wiki/%E6%9C%AF%E8%AF%AD%E7%BF%BB%E8%AF%91%E7%BA%A6%E5%AE%9A)

Here is some words I found we should specify
1. end-bundlers
2. unbundled:
3. built modules
4. no-bundle 
5. pre-bundling
6. rebasing  / public path rebase
7. first-class support

**Comment by QC-L** [comment]
That's great. We can discuss it in [discussions](https://github.com/vitejs/docs-cn/discussions) like windicss.
