### ISSUE TITLE
你会看到它在整个文档中用 <root> 表示，这个<root>具体指什么

### ISSUE THREAD

**Issue by mikexfreeze** [vitejs/docs-cn#190]
在文档中的 开始>index.html与项目根目录 章节中有这样一句话“你会看到它在整个文档中用 `<root>` 表示”
请问这个`<root>` 是不是指 `<div id="root">` 还是其他含义？

**Comment by ShenQingchuan** [comment]
Hi，同学你好。很抱歉给你的理解造成了疑惑，我们会立刻优化这个地方的翻译。

这里的英语原文是：
You will see it referenced as `<root>` throughout the rest of the docs.

妥当的翻译应是：
你将会在接下来的文档中看到根目录以 `<root>` 代称。

**Comment by ShenQingchuan** [comment]
温馨提示另外一个小 Tip ：
可能同学你还不太知道，在 Github 的 Markdown 编辑器中直接输入 `<root>`  这六个字符而不将它用反引号扩起来，会被识别为一个 HTML 标签，将无法正常显示出来

以后一定要记得编辑完 issue 后点一下 Write 旁边的 Preview 看看效果哦！

**Comment by ShenQingchuan** [comment]
为了帮助同学理解，你可以看到：

https://cn.vitejs.dev/guide/assets.html#the-public-directory

在文档这里：
> 目录默认是 `<root>/public`，但可以通过 `publicDir` 选项来配置。

这里就用到了这个 `<root>`，他是一个符号，帮助你阅读文档时快速理解文件的相对定位位置。

**Comment by mikexfreeze** [comment]
明白了，谢谢
