### ISSUE TITLE
vite ssr

### ISSUE THREAD

**Issue by yang867381349** [vitejs/docs-cn#199]
有关vite ssr 中。比如我需要借助 三方的ui 插件来实现一些需求功能。
 element-plus 中的 Cascader 级联选择器 不可以使用和其它小部分组件
 和
 naiveui 在ssr中的使用 任然遇到我们开发者无法解决的问题。
 ssr 中在每个框架也好库的引入方式也好，都有自己的标准！！！

**Comment by ShenQingchuan** [comment]
没有明白你的问题是什么。
你是想说 Vite 如何对这些第三方框架做 SSR 支持么？

Native-ui  的作者最近新建了一个仓库 作为 Native UI SSR 实践的一个范例，你可以持续关注与跟进：
https://github.com/07akioni/naive-ui-vite-ssr

另外本仓库是 文档仓库，若有使用方面的问题请去往 Vite 这个工具的官方仓库提 issue 哟。
