### ISSUE TITLE
绝对路径怎么配置？

### ISSUE THREAD

**Issue by yuri-li** [vitejs/docs-cn#206]
//测试文件的路径： test/components/HelloWorld.spec.ts
import HelloWorld from '../../src/components/HelloWorld.vue'

![image](https://user-images.githubusercontent.com/7019517/125743785-84706854-421a-4395-a1de-aa4dd5f01258.png)

**Comment by ShenQingchuan** [comment]
对不起，没有太理解您说的问题，另外这里是中文文档仓库，不接受 Vite 的用法问题咨询哦，谢谢合作。
