### ISSUE TITLE
文档错误

### ISSUE THREAD

**Issue by Lzy49** [vitejs/docs-cn#225]
- bug 页面：https://cn.vitejs.dev/guide/assets.html#new-url-url-import-meta-url
- 问题：
![image](https://user-images.githubusercontent.com/26904555/129193709-84e7524f-d00a-4869-9b90-866d9ac2adba.png)
- 该链接跳转url多了一个 `<wbr/>`
- 英文文档同样存在该bug

**Comment by QC-L** [comment]
收到，我看了下，这个属于 vitepress 造成的 bug，我们看下，非常感谢。
