### ISSUE TITLE
vite使用可选链操作手机端浏览器项目报错

### ISSUE THREAD

**Issue by sbq17** [vitejs/docs-cn#236]
当我使用vite创建vue3项目时，使用了可选链操作，代码如下
![image](https://user-images.githubusercontent.com/45897218/131106347-ffc748ef-aeae-4e91-9c23-9e56364694aa.png)
![image](https://user-images.githubusercontent.com/45897218/131106373-02d7b887-0f74-4452-bab5-62dac4153200.png)
PC端浏览器是正常运行的
![40ed5ac5dd0d45cec89d31935e856a6](https://user-images.githubusercontent.com/45897218/131106466-6ab41281-3435-4454-9f5a-add023b36d41.jpg)
当我使用vite创建react时，使用可选链操作也会报错
我使用vue ui创建vue3项目时，就不会出现问题
这是我的依赖 vue3
![image](https://user-images.githubusercontent.com/45897218/131106627-49d74ebe-f2eb-4395-9c94-6e17f6e5933e.png)
这是我测试的react项目依赖
![image](https://user-images.githubusercontent.com/45897218/131106694-f9eceebb-a88b-4663-921e-034f0a1d1a23.png)

**Comment by ShenQingchuan** [comment]
您好，这里是 Vite 中文文档的 Issue 区，如果有任何使用问题，请前往 Vite 官方 issue 区进行提问。
我们这里不提供 Vite 的使用问题解答。谢谢合作！

**作为我个人的善意提醒：**
1. 提出 issue 虽然贴上相应信息的图片是好方法之一，但提问前最好更多的思考下背后的原因，找到问题的真正核心点。
  这样才能形成高质量的 issue 问答，最有效率地解决问题。

2. 我对你在 ComputedRef 上直接使用 可选链操作符 `?.` 表示好奇和疑问，为什么不是 `.value?.` 呢？
3. 首先应该查看 Vite 在运行时，Vue 这个库对 .vue 单文件组件处理后生成的 js 文件里是否仍含有可选链符号 `?.`。
  如果编译产物 js 文件中确实有，那么接着来了两个问题：
  1. 手机端浏览器的实际内核版本是否支持原生 ESM 加载？
  2. 手机端浏览器的实际内核版本是否支持了可选链的提案？

以上建议和推测仅作为我看到你的问题和描述后的个人理解，或许也有一些错误，但还是希望能对你有所帮助。

**Comment by sbq17** [comment]
感谢您的回复，给您造成了额外的工作量，其实我.value?.我也是尝试过了，鉴于工作经验缺乏，没有想到查看问题，而是直接抛出疑问，十分抱歉




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vitejs/docs-cn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月5日(星期天) 晚上11:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vitejs/docs-cn] vite使用可选链操作手机端浏览器项目报错 (#236)





 
您好，这里是 Vite 中文文档的 Issue 区，如果有任何使用问题，请前往 Vite 官方 issue 区进行提问。
 我们这里不提供 Vite 的使用问题解答。谢谢合作！
 
作为我个人的善意提醒：
  
 
提出 issue 虽然贴上相应信息的图片是好方法之一，但提问前最好更多的思考下背后的原因，找到问题的真正核心点。
 这样才能形成高质量的 issue 问答，最有效率地解决问题。
 
 
 
我对你在 ComputedRef 上直接使用 可选链操作符 ?. 表示好奇和疑问，为什么不是 .value?. 呢？
 
 
 
首先应该查看 Vite 在运行时，Vue 这个库对 .vue 单文件组件处理后生成的 js 文件里是否仍含有可选链符号 ?.。
 如果编译产物 js 文件中确实有，那么接着来了两个问题：
 
 
 
手机端浏览器的实际内核版本是否支持原生 ESM 加载？
 
 
 
手机端浏览器的实际内核版本是否支持了可选链的提案？
 
  
以上建议和推测仅作为我看到你的问题和描述后的个人理解，或许也有一些错误，但还是希望能对你有所帮助。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
