### ISSUE TITLE
PRs are not effective enough | 目前 PR 不够高效

### ISSUE THREAD

**Issue by KnowsCount** [vitejs/docs-cn#25]
I have been participating in this the development of this repo recently, and there is one small thing that I observed: most of the pull requests opened only make fixes upon one single sentence or character. Whereas, alas, merging those pull requests would add two commits to the repo, which will, eventually, lead to a huge amount of commits. Therefore, I, for one, reckon it a better idea to open the discussion function or simply to open a issue for people to suggest fixes and changes. This way, one single commit from you could resolve many an issue. Moreover, @ShenQingchuan, formatting issues that took place in my pull request would be diminished #14 accordingly.

---

最近，我一直在参与这个 repo 的开发，并注意到了一件小事：大多数 PR 只对一个句子或一个字符进行修复。而合并这些拉取请求，则会给这个 repo 带来两次 commit，最终给这个 repo 带来一大堆  @commits。因此，我认为最好的办法是开放讨论功能，或者干脆开放一个问题，让大家提出修正和修改。这样一来，你那边一次 commit 就可以解决很多问题。另外，我之前那 PR （#14）中发生的格式化问题也会相应减少。

---

BTW 我用中文还是英文？

**Comment by ShenQingchuan** [comment]
中文文档仓库中 可以自由使用中文提出 issues

**Comment by KnowsCount** [comment]
> 中文文档仓库中 可以自由使用中文提出 issues

好的好的，我主要是顾及到会不会有 vitejs 组织的外国人看哈哈哈哈。所以你觉得怎么说？

**Comment by ShenQingchuan** [comment]
文档有 typo 之类的小 commit 属于正常现象，vite 本身仓库中也有不少 commit 是仅修改几个字符的。

**Comment by KnowsCount** [comment]
理解。
