### ISSUE TITLE
vite 在react-ts 中热更新速度慢

### ISSUE THREAD

**Issue by cll123456** [vitejs/docs-cn#26]
本人在使用vite 搭建的react-ts 的项目中，项目启动非常块，但是每当我启动好后，我在.tsx 文件中修改一些代码，浏览器并没有更新。刷新浏览器页面页没有生效。只有我重新 `npm run dev` 才会生效。目前我一直在寻找解决办法，苦于自己的英文是个二把刀。我的配置文件是这样的：
`import reactRefresh from '@vitejs/plugin-react-refresh'
import { defineConfig } from 'vite'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [reactRefresh()]
})
`
package.json 一开始的vite 是2.0.0的bata，目前是这样的：
`"devDependencies": {
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@vitejs/plugin-react-refresh": "^1.3.1",
    "typescript": "^4.1.2",
    "vite": "^2.0.1"
  }
}`

希望看到的能留意一下我的问题，并且目前的解决方案是啥？ 感谢看到这个问题的。

**Comment by ShenQingchuan** [comment]
参见 Readme.md，关于 vite 的使用问题请不要在文档仓库内提，谢谢合作。
