### ISSUE TITLE
修改Vue3的defineProps的默认值，不会触发热更新

### ISSUE THREAD

**Issue by Xyuan-abs** [vitejs/docs-cn#278]
![image](https://user-images.githubusercontent.com/64180387/137851978-b368f853-dd03-44a1-858e-83807f250cfc.png)

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**。

这里不是 Vite 的中文社区，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
