### ISSUE TITLE
打包之后运行vite preview 浏览器报ReferenceError: module is not defined，这是什么问题呢？

### ISSUE THREAD

**Issue by wangmhaha** [vitejs/docs-cn#280]

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**。

这里不是 Vite 的中文社区，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
