### ISSUE TITLE
ReferenceError: global is not defined

### ISSUE THREAD

**Issue by iHalo-dev** [vitejs/docs-cn#281]
import mqtt from 'mqtt'
produces error： ReferenceError: global is not defined

**Comment by boswellgao** [comment]
I have the same error: Some other dependencies like [url-search-params](https://github.com/WebReflection/url-search-params)
```javascript
URLSearchParams = (module.exports = global.URLSearchParams || URLSearchParams);
```
the global is not defined,and to solve this error,I have to remove the global in node_modules and remove the cache dir

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**。

这里不是 Vite 的中文社区，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
