### ISSUE TITLE
Sourcemap for "D:/xxx/xxx/node_modules/.vite/react-dom.js" points to missing source files

### ISSUE THREAD

**Issue by miss-tree** [vitejs/docs-cn#284]
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import fs from 'fs'
import path from 'path'
import ractRefresh from '@vitejs/plugin-react-refresh'
import genericNames from 'generic-names'
import reactSvgPlugin from 'vite-plugin-react-svg'
const resolve = (url) => path.resolve(__dirname, url)

export default defineConfig({
  mode: 'development',
  base: './',
  server: {
    host: '0.0.0.0',// 公开 ip 访问服务
    port: 3456,
    open: true,
    // 设置为 true 强制使依赖预构建，当依赖变化时，需要更新一下预构建依赖
    force: true
  },
  define: {// 定义全局变量
    'process.env': process.env, // 让客户端代码读取到 process.env
  },
  esbuild: {
    loader: 'jsx',
    /** 在使用 VUE 项目要使用下面两个注释熟悉 */
    // jsxFactory: 'h',
    // jsxFragment: 'Fragment',

    include: /src.*\.jsx?$/,
    exclude: []
  },
  build: {
    outDir: './public/',
    brotliSize: false,
    chunkSizeWarningLimit: 100 * 1024,
  },
  plugins: [
    react(),
    // 为了各种打包报错，也没有热加载功能，  ==>html模板中增加引入 RefreshRuntime
    // 更改代码后整页刷新  ===> 客户端入口增加 import.meta.hot.accept()
    // ractRefresh(),
  ],
  optimizeDeps: {
    esbuildOptions: {
      plugins: [
        {
          // jsx 文件默认不走 jsx 编译，需要配置
          // https：//github.com/vitejs/vite/discussions/3448
          name: 'load-js-files-as-jsx',
          setup (build) {
            build.onLoad({ filter: /src.*\.jsx?$/ }, async args => {
              return {
                loader: 'jsx',
                contents: fs.readFileSync(args.path, 'utf-8')
              }
            })
          }
        }
      ]
    },
    entries: resolve('./src/index.js'),
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, 'src')
    },
    extensions: ['.jsx', '.js']
  },
})

Sourcemap for "D:/xxx/webpack-react-ts/node_modules/.vite/react-dom.js" points to missing source files

**Comment by yzha5** [comment]
我也有这个，虽“不伤大雅”，但也无法容忍。请问解决了吗？

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**。

这里不是 Vite 的中文社区，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
