### ISSUE TITLE
how to import a component relatively

### ISSUE THREAD

**Issue by 949054042** [vitejs/docs-cn#297]
![image](https://user-images.githubusercontent.com/29389190/141766260-919cf98e-0f9d-4ed2-8372-e618e9f64ee6.png)

when i try to import a component by this way ,i got a error like this
.vue has no corresponding SFC entry in  the cache. This is a vite-plugin-vue2 internal error

**Comment by QQhuan** [comment]
Hello, this may be a version issue.  Issue #2068 may help u.

**Comment by QQhuan** [comment]
Hello, this may be a version issue.  Issue #2068 may help u.

**Comment by 949054042** [comment]
> Hello, this may be a version issue. Issue #2068 may help u.

没找到这个啊，请问具体是哪个

**Comment by QQhuan** [comment]
[2068](https://github.com/vitejs/vite/issues/2068)

**Comment by 949054042** [comment]
> [2068](https://github.com/vitejs/vite/issues/2068)

谢谢
