### ISSUE TITLE
vite打包不靠谱哦，直接卡在chunk(26)这里....

### ISSUE THREAD

**Issue by kensmaster** [vitejs/docs-cn#306]
网上的2种解决办法依然无效：
1、调整包告警的大小
vite.config.js
export default defineConfig({
  ...
  build:{
    chunkSizeWarningLimit:1000,
    }
  }
})

2、代码分解
export default defineConfig({
  ...
  build:{
    rollupOptions:{
      output:{
        manualChunks(id){ // 分包
          if(id.includes('node_modules')){
            return id.toString().split('node_modules/')[1].split('/')[0].toString();
          }
        }
      }
    }
  }
})

**能解决这问题吗？哪位大神知道呢，目前又用回webpack了**

**Comment by yyx990803** [comment]
1. 这里是文档翻译，不是提供支持的地方
2. 学会问问题，你提供的信息根本不足以让我们做出任何判断，没有可重现的仓库我们想帮你也没办法。

**Comment by kensmaster** [comment]
1.文档翻译也很其他人提了很多问题，不让提可以关了
2.学会回答问题吧。你看不懂至少标题的意思很明了吧，"打包卡住了"
