### ISSUE TITLE
vite + element-plus form里面的lable无法热更新

### ISSUE THREAD

**Issue by tanagang** [vitejs/docs-cn#307]
版本号vite：2.6.14
![image](https://user-images.githubusercontent.com/5810480/143515551-8e2c1c40-65da-433c-8168-2fe1221fea8e.png)
这里把class加上和去掉页面没有反应的，把template改成普通div是没有问题的

**Comment by Rexexe** [comment]
同问，好像组件的属性更换都不会触发热更新

**Comment by ShenQingchuan** [comment]
## Vite 使用问题相关 issue 统一处理

首先感谢你对 Vite 的支持，但这里是 Vite 官方中文文档的翻译项目相关 issue 的提交站。

这里不是 Vite 的中文社区，请不要在此提交关于 Vite 使用的问题或报 Bug。，请移步 Vite 主仓库 issue 区。

感谢你的配合。
