### ISSUE TITLE
For vue cli, there is a cookbook for debugging in vscode, but, for vite, there is nothing

### ISSUE THREAD

**Issue by softboy99** [vitejs/docs-cn#311]
For vue cli, there is a cookbook for debugging in vscode, but, for vite, there is nothing. we still use console.log or degger statements, which are invasive and need to be removed when publish. What we want is to set breakpoints in the code. but now it is not so good experience

**Comment by ShenQingchuan** [comment]
## Vite 使用问题相关 issue 统一处理

首先感谢你对 Vite 的支持，但这里是 Vite 官方中文文档的翻译项目相关 issue 的提交站。

这里不是 Vite 的中文社区，请不要在此提交关于 Vite 使用的问题或报 Bug。，请移步 Vite 主仓库 issue 区。

感谢你的配合。
