### ISSUE TITLE
@rollup/plugin-inject引入jquery之后，console.log定位不到文件位置

### ISSUE THREAD

**Issue by 949054042** [vitejs/docs-cn#316]
![image](https://user-images.githubusercontent.com/29389190/144216459-748e02fd-f4da-4ad6-bd70-3ab375fdf065.png)
![image](https://user-images.githubusercontent.com/29389190/144216580-b5201f2f-9692-4d4f-8b9a-8e0c914c1812.png)

**Comment by ShenQingchuan** [comment]
## Vite 使用问题相关 issue 统一处理

首先感谢你对 Vite 的支持，但这里是 Vite 官方中文文档的翻译项目相关 issue 的提交站。

这里不是 Vite 的中文社区，请不要在此提交关于 Vite 使用的问题或报 Bug。，请移步 Vite 主仓库 issue 区。

感谢你的配合。
