### ISSUE TITLE
vite JavaScriptapi 能否接收配置项数据

### ISSUE THREAD

**Issue by miui8824** [vitejs/docs-cn#326]
vite JavaScriptscript createServer API
目前该api 用 configFile 配置文件 作为启动配置项 
后期能否支持数据配置呢？

**Comment by ShenQingchuan** [comment]
## Vite 使用问题相关 issue 统一处理

首先感谢你对 Vite 的支持，但这里是 Vite 官方中文文档的翻译项目相关 issue 的提交站。

这里不是 Vite 的中文社区，请不要在此提交关于 Vite 使用的问题或报 Bug。，请移步 Vite 主仓库 issue 区。

感谢你的配合。
