### ISSUE TITLE
vue3使用yarn start启动获取时间显示正常,用vite启动会报错Invalid Date

### ISSUE THREAD

**Issue by YamssL** [vitejs/docs-cn#327]
使用到vue antd 的日历组件,问题发生在默认值获取的时候

**Comment by ShenQingchuan** [comment]
## Vite 使用问题相关 issue 统一处理

首先感谢你对 Vite 的支持，但这里是 Vite 官方中文文档的翻译项目相关 issue 的提交站。

这里不是 Vite 的中文社区，请不要在此提交关于 Vite 使用的问题或报 Bug。，请移步 Vite 主仓库 issue 区。

感谢你的配合。
