### ISSUE TITLE
ts+vite 报错[plugin:plugin-import-redirect] Parse error @:28:16

### ISSUE THREAD

**Issue by zsuk** [vitejs/docs-cn#329]
正常引用格式，但是报错，而且无法识别@material-ui/core `的标签，packagejson已安装依赖
![image](https://user-images.githubusercontent.com/43307613/145943600-386b24d2-c3bf-4e76-b821-a089fefb99b2.png)

**Comment by ShenQingchuan** [comment]
## Vite 使用问题相关 issue 统一处理

首先感谢你对 Vite 的支持，但这里是 Vite 官方中文文档的翻译项目相关 issue 的提交站。

这里不是 Vite 的中文社区，请不要在此提交关于 Vite 使用的问题或报 Bug。，请移步 Vite 主仓库 issue 区。

感谢你的配合。
