### ISSUE TITLE
使用vscode+vue3.0+ts开发时需要怎么配置让断点调式正常

### ISSUE THREAD

**Issue by aohanhe** [vitejs/docs-cn#338]
现在在使用断点 chrome调式时工作是不正常的，经常会断在不正常的位置，删除了断点之后也会中断代码。请问一下这个问题是要怎么来解决？

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
