### ISSUE TITLE
vite与cli创建的项目配置文件对比,无websocket转发

### ISSUE THREAD

**Issue by tmkmk** [vitejs/docs-cn#342]
在原vue.config.js中
`proxy: {
      "/": {
        target: "http://localhost:3001",
        changeOrigin: true,
        pathRewrite: {
          "^/": "",
        },
      },
    },`
如此配置.则可以转发所有 vue开发端没有的资源. 例如一些静态资源,如果vue开发服务器没有,则会读取所设置的proxy 进行拉取,所有post请求也将会转发, 连接的websocket也会被转发.
而在vite.config.ts中配置
`
  proxy: {
      "/": {
        target: "http://localhost:3001/",
        // target:"https://mysl.tianyuekeji.ltd",
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\//, ""),
      },
    },
`
则仅将 "/" 之后的 post/get请求进行无脑转发,没有进行一些判定,到底哪些资源是确实需要转发,而哪些又不需要转发.并且没有覆盖到websocket,

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
