### ISSUE TITLE
vite的库模式，ES6+如何转换ES5，或者如何配置？

### ISSUE THREAD

**Issue by weijuer** [vitejs/docs-cn#344]
如题，另外@vitejs/plugin-legacy对于库模式不适用，麻烦告知如何配置，谢谢

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
