### ISSUE TITLE
每次保存页面都会刷新？

### ISSUE THREAD

**Issue by a524313390** [vitejs/docs-cn#345]
我记得之前每次保存页面不会重新刷新的，现在怎么每次保存都需要刷新？

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
