### ISSUE TITLE
vite 启动失败

### ISSUE THREAD

**Issue by Qthon** [vitejs/docs-cn#346]
![image](https://user-images.githubusercontent.com/57051723/147585523-b906e418-3f31-4ab1-ba56-bf1ec4dae27d.png)

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
