### ISSUE TITLE
index.html 获取环境变量?

### ISSUE THREAD

**Issue by chenguzhen87** [vitejs/docs-cn#356]
![image](https://user-images.githubusercontent.com/28331609/148360467-ef1efaf8-d49f-45db-99cd-eeb1f6f088c2.png)
我需要在箭头处获取不同环境下变量值

**Comment by Rexexe** [comment]
直接import.meta.env.XXXX就可以了，但是这里还有个问题，他会自己加上引号，我在title上面使用环境变量结果不是我要的
![image](https://user-images.githubusercontent.com/27289798/149470632-ed311fc6-5ce0-490a-af53-2ca5ad379fff.png)
![image](https://user-images.githubusercontent.com/27289798/149470691-78d60a1e-d717-400f-9cd2-9b30575e799d.png)

**Comment by chenguzhen87** [comment]
这样不行啊，我在一个字符串

**Comment by Rexexe** [comment]
> 这样不行啊，我在一个字符串

https://cn.vitejs.dev/guide/env-and-mode.html#env-files
你的环境变量文件有吗

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**。

这里不是 Vite 的中文社区，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
