### ISSUE TITLE
vite启动成功后 运行失败报错 依赖重新删除下载后依然报错

### ISSUE THREAD

**Issue by bryant-number** [vitejs/docs-cn#357]
![image](https://user-images.githubusercontent.com/19608728/148477019-7e7df38e-39f1-43f9-9b06-ecda9a2f223d.png)

![image](https://user-images.githubusercontent.com/19608728/148477070-8e4f6c12-7f97-4e7f-b498-1d1539865f84.png)

**Comment by fufengren** [comment]
mee too 
![image](https://user-images.githubusercontent.com/76684168/148667977-1d8249e5-83ae-4905-8b3f-469d63a32d90.png)

**Comment by a233894432** [comment]
最近咋大家都 在做代码 平台   .lowcode...

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**。

这里不是 Vite 的中文社区，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。

**Comment by bryant-number** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
