### ISSUE TITLE
无法编译node:前缀的引用

### ISSUE THREAD

**Issue by caoailin** [vitejs/docs-cn#359]
像项目引用了got，用vite无法编译使用，因为使用了 import node: 前缀

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**。

这里不是 Vite 的中文社区，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。

**Comment by caoailin** [comment]
只需要设置external node:前缀即可
