### ISSUE TITLE
vite 2.6~2.7 WebSocket proxy代理，服务端断开连接后，dev模式崩溃

### ISSUE THREAD

**Issue by zsj1029** [vitejs/docs-cn#361]
## 问题
- proxy文件设置ws代理

![image](https://user-images.githubusercontent.com/10348238/149061034-0156fe83-fbe7-4a24-8090-5ffaf7c09071.png)

- 服务端只要断开连接，页面正常逻辑会websocket会重连几次，客户端正常错误信息
![image](https://user-images.githubusercontent.com/10348238/149061920-142ef61e-543c-42ba-b5fa-f6bd4e7c3bba.png)
然后vite的dev报错崩溃，但是找不到错误断点，报错信息也很模糊
- 如果服务端不断，没有问题
- 关闭ws代理，走ws ip直连，一切正常

## 期望
vite dev模式正常，不会崩溃退出，目前崩溃后只能重新执行dev

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**。

这里不是 Vite 的中文社区，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
