### ISSUE TITLE
mac上build会报错return this._head?.value;在win上倒是正常打包。

### ISSUE THREAD

**Issue by qiujunyu** [vitejs/docs-cn#364]
救命~sos

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
