### ISSUE TITLE
vite如何在index.html中区分环境加载不同的js

### ISSUE THREAD

**Issue by naduohua** [vitejs/docs-cn#368]
目的：index.html根据开发环境、生产环境加载不同的js脚本

类似webpack这种模板语言，在vite中应该如何实现？

```html
<head>
<% if (process.env.NODE_ENV === 'production') { %>
  <script src="//xx.com/xx.js"></script>
<% } %>
</head>
```

**Comment by collins401** [comment]
插件解决 `vite-plugin-html`

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
