### ISSUE TITLE
Vite 中文文档翻译小组群聊

### ISSUE THREAD

**Issue by wjq990112** [vitejs/docs-cn#37]
建了一个微信群供大家一起翻译讨论，原则上不接收不参与翻译的同学。

<img src="https://user-images.githubusercontent.com/45777252/108696243-3f92b980-753c-11eb-9a2d-23868c04fc7e.png" width="300px" />

**Comment by wjq990112** [comment]
@ShenQingchuan @KnowsCount

**Comment by Ivocin** [comment]
@wjq990112  来了，好多人啊。

**Comment by okbug** [comment]
还有更新嘛
