### ISSUE TITLE
vite如何配置css sourceMap

### ISSUE THREAD

**Issue by hjyyang** [vitejs/docs-cn#371]
css 的源映射在复杂项目中可使我们更快的知道修改那个css文件，在vite中要如何配置该功能？

**Comment by hjyyang** [comment]
是否可以说明下该功能缺失的原因呢？

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
