### ISSUE TITLE
vite可以开发nestjs吗

### ISSUE THREAD

**Issue by CloudWoR** [vitejs/docs-cn#378]
nestjs的打包一直没搞懂，打包后不包含node_modules，还得将node_modules整个手动复制到服务器上面（局域网服务器），所以想请教一下如果用vite开发nestjs可行吗？

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
