### ISSUE TITLE
前端使用GET请求通过proxy代理后GET请求Request Body丢失，后端获取数据为空（{}）

### ISSUE THREAD

**Issue by DoneLyGit** [vitejs/docs-cn#393]
向后端发送请求方法
![image](https://user-images.githubusercontent.com/36059904/156730105-77b485ca-a44a-4bba-ae5f-d8281dd5c3aa.png)
proxy 代理设置
![image](https://user-images.githubusercontent.com/36059904/156730224-465d3492-07ac-4c10-a87d-bece059e8722.png)
当前端发送GET请求时后端获取Request Body 时数据为空
![image](https://user-images.githubusercontent.com/36059904/156730445-68e340f3-b711-4a5a-ae36-d938dc4f95d4.png)

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
