### ISSUE TITLE
dotenv与node的env如何兼容呢

### ISSUE THREAD

**Issue by jun747093801** [vitejs/docs-cn#397]
目的：在开发环境使用vite，发布依旧使用webpack打包
1. 传统webpack打包的环境变量，例如在vue文件通常是使用process.env.xxx获取的
2. 而vite是使用import.meta.env.xxx获取
如果我要兼容开发，该怎么设置呢

**Comment by ShenQingchuan** [comment]
https://cn.vitejs.dev/guide/env-and-mode.html#env-variables

没太懂您的意思。

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
