### ISSUE TITLE
域名部署与集成发布支持

### ISSUE THREAD

**Issue by ShenQingchuan** [vitejs/docs-cn#4]
@yyx990803 

目前中文文档仓库已经建立完成，申请 https://cn.vitejs.dev 域名部署支持。

**Comment by ShenQingchuan** [comment]
@yyx990803 近期可以域名部署和文档发布么？

**Comment by sodatea** [comment]
已部署

**Comment by ShenQingchuan** [comment]
> 已部署

好的，感谢支持。

之后推送更新会同步更新部署么？
