### ISSUE TITLE
把中文文档部署在内网linux上esbuild报错，windows可以正常使用

### ISSUE THREAD

**Issue by onlinegenerator** [vitejs/docs-cn#400]
let child = child_process.spawn(command, args.concat(`--service=${"0.14.22"}`, "--ping"), {
    windowsHide: true,
    stdio: ["pipe", "pipe", "inherit"],
    cwd: defaultWD
  });
 child.stdin 为undefined

**Comment by ShenQingchuan** [comment]
目前根据您的描述看不出是什么问题，可否给出更详细的报错信息？

**Comment by onlinegenerator** [comment]
邮件已收到!

**Comment by onlinegenerator** [comment]
![de6e8c3f9be1ff3d851d6acb45c1898](https://user-images.githubusercontent.com/31384024/157560881-3e5431a3-f7ca-4e87-82e3-349f0e49d798.jpg)

**Comment by onlinegenerator** [comment]
![9e1f4b44e4e0a1d46acb723d067aebf](https://user-images.githubusercontent.com/31384024/157561090-e21c09d9-01d2-4d2c-b9a7-20511f99ed85.jpg)

**Comment by ShenQingchuan** [comment]
看到你的node版本是11.7.0，升级到v14试一试哈。

另外这个和中文文档翻译工作无关。这里暂时先关闭issue但不lock，可以后续继续讨论。
