### ISSUE TITLE
官网事例无法正常使用

### ISSUE THREAD

**Issue by Zero-Qi** [vitejs/docs-cn#402]
pnpm create vite my-vue-app -- --template vue

 ERROR   ERROR  Unknown option: 'template'
Did you mean 'test-pattern'? Use "--config.unknown=value" to force an unknown option.

**Comment by ShenQingchuan** [comment]
create-vite ，中间要加短横线

**Comment by Zero-Qi** [comment]
pnpm create-vite my-vue-app -- --template vue
这样也不行啊

**Comment by ShenQingchuan** [comment]
> pnpm create-vite my-vue-app -- --template vue 这样也不行啊

您好，已经重新更新了我的回答。抱歉之前给您造成的困扰，
