### ISSUE TITLE
vscode 开着vite服务器，修改工作区文件出现卡顿

### ISSUE THREAD

**Issue by wan9alex** [vitejs/docs-cn#416]
只要开着vite的3000服务器，对工作区文件更名，移动，删除操作都会卡顿，且导致操作失败，关闭3000服务器，操作立马申效，开着3000，去资源管理器操作文件依然被vite禁止，如何解决？

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
