### ISSUE TITLE
怎么样配置能直接用file协议访问打包后的文件

### ISSUE THREAD

**Issue by kingboVIP** [vitejs/docs-cn#418]
Access to script at 'file:///H:/code/lightApp/vite-project/dist/assets/index.f888e0f1.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.

**Comment by ShenQingchuan** [comment]
没太懂你的意思，你是想用 File 协议在浏览器中打开你打包好的文件吗？现在是浏览器控制台报了错说 Cross origin request 不支持 file 协议？似乎 Vite 对此并帮不上任何忙 ...
