### ISSUE TITLE
vite 不支持 mobx6 inject 方法，很失望，也很无助

### ISSUE THREAD

**Issue by lsj162** [vitejs/docs-cn#427]
. . .
export default inject("mobxStore")(observer(Page));
. . .

yarn build 后

yarn preview 后

浏览器空白，报错：react 未定义，去掉mobx 页面组件引用就没问题

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
