### ISSUE TITLE
build失败 但是这个错误提示不明白

### ISSUE THREAD

**Issue by huzidabanzhang** [vitejs/docs-cn#430]
![image](https://user-images.githubusercontent.com/26140439/163173697-ea051de1-1626-4ba4-b2c6-db5ee788da67.png)

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
