### ISSUE TITLE
"import.meta" is not available in the configured target environment ("es2015") and will be empty

### ISSUE THREAD

**Issue by wade3po** [vitejs/docs-cn#433]
"import.meta" is not available in the configured target environment ("es2015") and will be empty
use npm init @vitejs/app create project
use mockjs vite-plugin-mock,when use import.meta.glob,is error:
"import.meta" is not available in the configured target environment ("es2015") and will be empty

api show:
Vite 支持使用特殊的 import.meta.glob 函数从文件系统导入多个模块
这只是一个 Vite 独有的功能而不是一个 Web 或 ES 标准

setting where？

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
