### ISSUE TITLE
dev开发可正常运行，build也是正常打包，但是生产环境页面会抱一个阻塞错误，导致页面空白

### ISSUE THREAD

**Issue by liuwuqingnian** [vitejs/docs-cn#434]
不知道hrm 和 打包后有什么不一样。 安装了 stream-browserify ，报错是h.from && h.alloc && h.allocUnsafe && h.allocUnsafeSlow。h是未定义，应该是个buffer 。怀疑是引入的 xml2js 包

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
