### ISSUE TITLE
how does this happen? 

### ISSUE THREAD

**Issue by squaingh** [vitejs/docs-cn#437]
![image](https://user-images.githubusercontent.com/27183034/163572453-820d7e0e-18ce-484d-8768-4822c2e736d8.png)

**Comment by squaingh** [comment]
node: 12.20.2
npm: 6.14.11
mac: 10.11.6 (15G31)

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
