### ISSUE TITLE
本地运行该项目，打开页面报错 404 

### ISSUE THREAD

**Issue by trueLoving** [vitejs/docs-cn#439]
## Bug Description

![image](https://user-images.githubusercontent.com/44056372/163676441-2cd2c58d-d9a9-4d3b-b87a-04db0d310baa.png)

点击 “指引 -> 环境变量与模式” 和  “指引 -> 服务端渲染（SSR）” ，页面跳转到 404 且控制台有报错

## Reproduction

1. git clone https://github.com/vitejs/docs-cn.git
2. cd docs-cn 
3. npm install
4. npm run dev
5. 点击“指引/(环境变量与模式和服务端渲染)” 

## System Info
System: Window10 WSL
Node: v16.14.2
Npm: 8.5.0

**Comment by ShenQingchuan** [comment]
推荐先安装 pnpm 然后 pnpm install 然后再跑一下试试

**Comment by ShenQingchuan** [comment]
因为该讨论长期不活跃，因此暂时关闭。
如果需要请 Reopen
