### ISSUE TITLE
文档搜索挂了

### ISSUE THREAD

**Issue by Amorites** [vitejs/docs-cn#446]
英文版站点是好的

现在发出请求的地址是  `https://undefined-dsn.algolia.net/1/indexes/*/queries?x-algolia-agent=Algolia%20for%20JavaScript%20(4.8.5)%3B%20Browser%20(lite)%3B%20docsearch%20(3.0.0)%3B%20docsearch-react%20(3.0.0)%3B%20docsearch.js%20(3.0.0)&x-algolia-api-key=b573aa848fd57fb47d693b531297403c&x-algolia-application-id=undefined`

**Comment by ShenQingchuan** [comment]
搜索功能该 issue 等待 @yyx990803 重新配置后生效

**Comment by ShenQingchuan** [comment]
close by https://github.com/vitejs/docs-cn/commit/037908359ebea8951718680aba9c7d44896bd1f8
