### ISSUE TITLE
用Jenkins打包发布成功后，访问页面时报这个错误，index:1 Uncaught TypeError: Failed to resolve module specifier "vue". Relative references must start with either "/", "./", or "../".

### ISSUE THREAD

**Issue by lipengfei00** [vitejs/docs-cn#451]
![image](https://user-images.githubusercontent.com/38172791/165667655-9163d030-c885-4bb6-8a9d-7c8a5d22091a.png)

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
