### ISSUE TITLE
ssr示例项目的vue和react链接失效。

### ISSUE THREAD

**Issue by co2color** [vitejs/docs-cn#474]
https://cn.vitejs.dev/guide/ssr.html
![image](https://user-images.githubusercontent.com/34681224/169764819-8662e508-1a77-4eb3-ba66-233fd9233b71.png)

**Comment by co2color** [comment]
![image](https://user-images.githubusercontent.com/34681224/169764753-73b3c1cf-238d-4d32-9828-6665cada5ccf.png)

**Comment by ShenQingchuan** [comment]
后续更新发下个版本的文档时会修复。
