### ISSUE TITLE
「动态导入 polyfill」翻译可能存在歧义

### ISSUE THREAD

**Issue by ipid** [vitejs/docs-cn#50]
[guide/build.md](https://github.com/vitejs/docs-cn/blob/main/guide/build.md) 第 9 行中写道：

> 一个轻量级的 [动态导入 polyfill](https://github.com/GoogleChromeLabs/dynamic-import-polyfill) 也会同时自动注入。

我自己看这个翻译的时候就误会了，因为「动态导入 polyfill」听起来就像是「项目中所需要的 **polyfill** 会被**自动**地**导入**到项目中」，让我以为 Vite 会像 webpack 一样自动把所需要的 polyfill 导入到项目里。实际上，这里的「动态导入」指的是 ES6 里的一个特性。下文中也说了 polyfill 是不会自动导入的，所以我读文档的时候就纠结了很久。如果改成「对 import() 函数的 polyfill」或者「对动态导入这一特性的 polyfill」会不会更好？

**Comment by ShenQingchuan** [comment]
明白您的意思了，是非常好的建议！
Let's see the PR later !
