### ISSUE TITLE
the docs error about blob

### ISSUE THREAD

**Issue by 787352714** [vitejs/docs-cn#505]
![image](https://user-images.githubusercontent.com/18625708/175197371-a5be06c9-7b8d-4294-9f03-8b53f83bfc7f.png)

use array as arguments in blob is invalid

**Comment by 787352714** [comment]
![image](https://user-images.githubusercontent.com/18625708/175197706-3425e329-3832-4e28-8ef8-d88cc02c14a5.png)

**Comment by ShenQingchuan** [comment]
Hi, 你的 Vite 版本是否是 2.9.12 及以下的 v2 版本 ？
当前的 Vite 中文文档的内容描述的是 v3 beta 版，`import.meta.glob` 的使用方法在 v3 发生了改变。

https://cn.vitejs.dev/guide/migration.html#importmetaglob

这个解答是否对你有帮助？
