### ISSUE TITLE
parentComponent.ctx.deactivate is not a function

### ISSUE THREAD

**Issue by mingshanjianke** [vitejs/docs-cn#521]
I add the key for router-view, but the hot updated is report the error when I update code. 

![image](https://user-images.githubusercontent.com/7993493/177711444-9d8ab67e-2cf7-4196-bf22-3d11e99aa01c.png)

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
