### ISSUE TITLE
无法访问v2中文文档

### ISSUE THREAD

**Issue by xinconan** [vitejs/docs-cn#525]
https://v2.vitejs.dev/ 这个是v2 的英文文档，里面的中文文档地址 https://cn.vitejs.dev/ 是v3的中文文档

**Comment by xinconan** [comment]
> v2 版中文文档 https://vitejs.cn/

这个好像不是官方的吧，不过可以凑合用

**Comment by YFengFly** [comment]
也可以用 https://github.com/vitejs/docs-cn/tree/v2 跑一下本地来临时查看
现在我连中文官网都打不开了😥

**Comment by ShenQingchuan** [comment]
目前暂时没有计划部署 Vite 2 的中文历史版本。
