### ISSUE TITLE
Linking from main docs and keeping URLs consistent across translations

### ISSUE THREAD

**Issue by patak-js** [vitejs/docs-cn#54]
Thanks a lot for all the work to maintain this translation ❤️ 

There was [a request](https://github.com/vitejs/vite/discussions/2796) to add a link from the main page to these docs

I discussed with @kiaking that is involved in the Japanase translation effort https://github.com/vuejs-jp/vite-docs-ja, and he told me that URLs are kept in English in their version. This is a good idea to enable us to link to translations directly from a given page, and not defaulting to the home page.

For the moment, I think we should add a link to the top of the docs that will go to the homepage

![image](https://user-images.githubusercontent.com/583075/113110763-bc821480-9207-11eb-9f39-e867bd97afca.png)

When you think that the translation is ready, it would be great to link both of them. Let me know if you would like me to create a PR to do that.

**Comment by ShenQingchuan** [comment]
OK，switching languages for a certain page sounds great! 

Would you like to provide a PR for this repo to implement that ？

The Chinese translation are ready for that.

**Comment by patak-js** [comment]
I don't know if we can do easily do it at this point, maybe we need support in VitePress for such a feat. The idea of having consistent URLs is to be able to do it at one point.

At least we should add a link that redirects to the home page for the moment. I'll send a PR to Vite and this repo to do that.

**Comment by ShenQingchuan** [comment]
OK, Let's see the PR...

**Comment by ShenQingchuan** [comment]
It seems like that a dropdown nav link in Vitepress can not be configured to not open a new browser tab, I just tested it locally...

Is it acceptable for now? Maybe we need a new issue for Vitepress to support that configuration.

**Comment by patak-js** [comment]
See https://github.com/vitejs/vite/pull/2803, I think there is value in adding this now, and we can later improve it. If you have the same change done for this repo, would you mind committing it yourself?

About the PR to modify the titles, I prefer that the translation team would handle that, as it is more involved than I thought (I think that internal links and main titles should also be replaced). This is the japanase config file: https://github.com/vuejs-jp/vite-docs-ja/blob/main/.vitepress/config.js

I also don't understand if the internal anchors of each page (subtitles) should be in English or in the local language. I think that even if anchors can not be easily swapped, it is better to have them respecting the locale. @kiaking, maybe you have some ideas here.

**Comment by ShenQingchuan** [comment]
I prefer use site current language... 

The current situation in https://cn.vuejs.org, the Chinese version nav link text is '多语言' rather than 'Languages' ...

**Comment by ShenQingchuan** [comment]
By the way... I quite doubt that we really need this... Generally, anyone in the world may start from the English version after he/she searched 'vite'... 
All we need is provide a full list of languages as the 'Languages' navlink in English site...

Is there really anyone which is a Chinese/Japanese, but first start from a Français documentation and wanna turn to his/her language site there?  🤣

**Comment by patak-js** [comment]
I think that it would be good to have the `Languages` link for consistency, and you can use '多语言' for it as it is in https://cn.vuejs.org/index.html. At least if I get to some future Spanish docs (my native language, I would like to have the option to switch). The only issue that I see is to keep the list of languages up to date, but a new language is not something that happens all the time.

**Comment by ShenQingchuan** [comment]
OK,
And one more thing we may discuss about... 

In Chinese site, is it necessary to keep the Chinese option in that list ?
For now, there isn't a Chinese('简体中文') option in https://cn.vuejs.org, I would like to be the same.

**Comment by ShenQingchuan** [comment]
Pull Request Merged.
