### ISSUE TITLE
vite配置proxy后，如何看到代理后的真实地址？以前用的logLevel失效

### ISSUE THREAD

**Issue by lty134679** [vitejs/docs-cn#546]

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。

另外，如果继续去主站点提问，你的问题描述可能需要更清晰一些。尽量多给出一些示例、重现等额外信息。
