### ISSUE TITLE
HMR的翻译

### ISSUE THREAD

**Issue by xfq** [vitejs/docs-cn#547]
https://webpack.docschina.org/concepts/hot-module-replacement/ 翻译的是「模块热替换」，而 https://cn.vitejs.dev/guide/features.html#hot-module-replacement 翻译的是「模块热重载」。

如果是刻意这么译的，是否可以添加到[词汇约定](https://github.com/vitejs/docs-cn/wiki/%E8%AF%8D%E6%B1%87%E7%BA%A6%E5%AE%9A)里去？

**Comment by ShenQingchuan** [comment]
这里应该是我的翻译失误，我之前以为 HMR 是 Hot-Module-Reload，但其实是 Replacement。我会发起一个 PR 将其改为 ”**热替换**“、并加入到词汇约定中。

**Comment by xfq** [comment]
谢谢！
