### ISSUE TITLE
升级 vite3.0.0后，启动报错了

### ISSUE THREAD

**Issue by qaz6237326** [vitejs/docs-cn#549]
我从2.x的项目文件 迁移到 3.0的项目中，然后vite升级到了3.0.0，npm run dev 的时候报了错误。

![image](https://user-images.githubusercontent.com/25748849/179969891-8d8f708c-85b5-4949-afb9-34ef9722a128.png)

下面是我的package.json配置
{
  "name": "vue3-demo",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite && node ./nodejs/webSocket.js",
    "build": "vite build",
    "serve": "vite preview"
  },
  "dependencies": {
    "@vitejs/plugin-vue-jsx": "^2.0.0",
    "@vue/babel-helper-vue-jsx-merge-props": "^1.2.1",
    "@vue/babel-preset-jsx": "^1.3.0",
    "axios": "^0.21.1",
    "element-plus": "^1.2.0-beta.5",
    "iconv-lite": "^0.6.3",
    "nodejs-websocket": "^1.7.2",
    "vue": "^3.2.4",
    "vue-router": "^4.0.10",
    "ws": "^8.2.3",
    "xterm": "^4.14.1",
    "xterm-addon-attach": "^0.6.0",
    "xterm-addon-fit": "^0.5.0"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^1.10.2",
    "@vue/compiler-sfc": "^3.0.5",
    "node-sass": "^6.0.1",
    "sass": "^1.42.1",
    "sass-loader": "^12.1.0",
    "vite": "^3.0.0"
  }
}

不知道如何解决该问题？

**Comment by ShenQingchuan** [comment]
请问你的 Node 版本是多少呢？
