### ISSUE TITLE
类型“ImportMeta”上不存在属性“env”

### ISSUE THREAD

**Issue by ashuicoder** [vitejs/docs-cn#551]
vite v3.0.0
<img width="730" alt="image" src="https://user-images.githubusercontent.com/47807522/180121506-6c7e6893-ac21-4eb3-8dd6-507e3cdb7878.png">

**Comment by ShenQingchuan** [comment]
你这里给到的信息也不足够解决和排查、似乎是你的项目内对 TypeScript 的周边配置有些东西漏了。

# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
