### ISSUE TITLE
vite3.0.0以上开启https,vue3服务不支持协议

### ISSUE THREAD

**Issue by gino-wisdom** [vitejs/docs-cn#570]
**1、vite3.0.0以上开启https**
此网站无法提供安全连接localhost 使用了不受支持的协议。
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

**2、打包时间**
使用@vitejs/plugin-legacy后，打包时间由30～50s，延长到7分钟左右

**Comment by xfq** [comment]
第一个问题见 https://cn.vitejs.dev/guide/migration.html#general-changes

**Comment by gino-wisdom** [comment]
> 第一个问题见https://cn.vitejs.dev/guide/migration.html#general-changes

谢谢 🙏
