### ISSUE TITLE
vite打包后发布在测试环境，一段时间不操作页面，再点击跳转页面时会有报错

### ISSUE THREAD

**Issue by LLLuojp** [vitejs/docs-cn#586]
Failed to load module script:The server responded with a non-JavaScript MIME type of "text/html".Strict MIME type checking is enforced for module scripts per HTML spec.
Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://xxx/xxx/xxx.js

会报以上错误，有解决办法吗？

**Comment by Dog4j** [comment]
就有些傻篮子不看readme么？
