### ISSUE TITLE
新建项目（Vite+Vue+TS），在vivo手机自带浏览器白屏

### ISSUE THREAD

**Issue by wangfeng211** [vitejs/docs-cn#589]
新建一个空项目Vite + Vue + TS,在vivo手机自带浏览器白屏，用调试工具发现在控制台显示报错：
“Unexpected token .”
"processRandomSelector is not defined"
"Unexpected token ."
"runCustomize is not defined"
"Unexpected token import"
"Unexpected token ."

手机系统版本： vivoX30，
型号：V1938CT，
Android 版本：9，
WebView：Android System WebView

**Comment by YFengFly** [comment]
请仔细阅读 README ，与中文文档无关的公共问题需按照引导进行提问。

**Comment by wangfeng211** [comment]
问题已解决，安装npm install @vitejs/plugin-legacy -D ，在vite.config.ts中 添加默认配置即可
