### ISSUE TITLE
vite创建的vue项目，打包后的文件本地预览报错

### ISSUE THREAD

**Issue by 18300618319** [vitejs/docs-cn#600]
vite创建的项目，打包后的文件本地预览报错
![image](https://user-images.githubusercontent.com/26192378/188781129-22a41ec1-d54b-41bc-a206-21a77aed697b.png)

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
