### ISSUE TITLE
打包忽略特定文件

### ISSUE THREAD

**Issue by myGitHubHuLin** [vitejs/docs-cn#601]
打包配置，如何使用正则排除部分文件。以及打包部分文件名称重新命名。

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
