### ISSUE TITLE
关于文档对vite.config.js的define描述不够清晰

### ISSUE THREAD

**Issue by zmyjs** [vitejs/docs-cn#605]
关于文档对vite.config.js的define描述主要有两处：

<img width="575" alt="微信截图_20220915093244" src="https://user-images.githubusercontent.com/20396642/190293394-f0015648-ce4b-4f75-acb5-1b88dc8a3ecb.png">

这里环境变量的示例，让我一度以为define就是通过**vite.config.js**传入的环境变量，通过`import.meta.env`读取。

第二处是这里：

<img width="564" alt="微信截图_20220915093606" src="https://user-images.githubusercontent.com/20396642/190293507-38f63225-d1d1-4b0e-aae1-3b570e728667.png">

但是也没说清楚是如何读取的，虽然提到了“定义全局常量”，但是`import.meta.env`从某种意义上说也是一种全局常量。

我测试了不生效一度以为是bug，然后去翻源码：

<img width="458" alt="微信截图_20220915094749" src="https://user-images.githubusercontent.com/20396642/190294194-4d99150e-83b0-42d9-b7fd-81a2b6da0bc9.png">

看到相关注释恍然大悟：原来是通过`window`读取的“全局”常量！回头看文档明白了全局是这个意思，这么看也没错，但是结合上下文还是有点误会的，如果稍微改进一下，给出一行小示例`window.__APP_ENV__`这样就可以减少一些误会。

我本来想PR的但是鉴于英文也要改，还是先提ls

**Comment by ShenQingchuan** [comment]
Hi，同学你好 ~

对于 define 的定义，其实文档有比较清晰的表述了：这个选项只是用于 **定义 `全局常量`**。
define 并不是把某个属性和值加到 `import.meta.env` 上。

从文档上应该不难看出，全局常量 和 `import.meta.env` 本质上是不同的概念。

`import.meta.env` 的更多详情，请同学阅读 [环境变量与模式](https://cn.vitejs.dev/guide/env-and-mode.html#env-variables-and-modes) 这一章节。
