### ISSUE TITLE
在初始安装依赖时，无法安装esbuild依赖

### ISSUE THREAD

**Issue by ApriCityAohan** [vitejs/docs-cn#676]
![839699901276193](https://user-images.githubusercontent.com/99794536/210468999-82ea774d-8102-4c2c-848d-70e9cc81e3d4.png)
![171712011276150](https://user-images.githubusercontent.com/99794536/210469002-22a9a3b7-2bb8-49d8-a0d4-95bf623782df.png)

vue+ts的模板
系统：Windows 11 家庭中文版   22H2   22621.963
vite4.0和vite3.2（第一个项目使用的，后续项目无法创建）
npm16.11.1 npm18.12.1
cnpm yarn
安装模式全部都使用了
网络问题也进行了排查

都试过基本全部无法下载依赖。
其他依赖正常，esbulid依赖无法安装。之前项目vite3.2正常，后续创建项目无法安装esbulid依赖。

**Comment by waynzh** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**，**请不要在此提交关于 Vite 使用的问题或报 Bug。** 请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
