### ISSUE TITLE
更新 VitePress 版本依赖

### ISSUE THREAD

**Issue by awxiaoxian2020** [vitejs/docs-cn#694]
VitePress 最近对 API 做了一些较大的变更，是否考虑更新依赖，以跟进相关更新。

参见 https://github.com/vuejs/vitepress/commit/8de2f4499d9364d85e6070ce4b94651a1902b101
https://github.com/vuejs/vitepress/commit/00abac611664e12710e5152d0259390b22c0e8ca
https://github.com/vuejs/vitepress/commit/5ae4fbde3843236e180e63e2cd2b7021efa0fad4

**Comment by xfq** [comment]
这个应该看英文原版是否更新？感觉最好和英文原版保持同样的依赖版本。

**Comment by awxiaoxian2020** [comment]
closed by https://github.com/vitejs/docs-cn/commit/41dc7fccaf53588ff858f652802a9a4d7c175b20.
