### ISSUE TITLE
现在的 vite 4.0 下载下来依赖的提示是错误的

### ISSUE THREAD

**Issue by zhengyimeng** [vitejs/docs-cn#697]
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/20783425/216587831-0211cda9-d224-4766-a22d-1b2e5fcc16df.png">
这时候我必须把 vue 改成 3.2.45 才可以正常工作！
<img width="310" alt="image" src="https://user-images.githubusercontent.com/20783425/216588029-ea37e2bb-5804-4ff1-b663-e377891d8d39.png">
mac 电脑
<img width="208" alt="image" src="https://user-images.githubusercontent.com/20783425/216588098-7d7e5be3-2a9f-46a8-b5b4-e07a7437c07f.png">

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
