### ISSUE TITLE
更换许可证

### ISSUE THREAD

**Issue by sxzz** [vitejs/docs-cn#703]
## 提议

更换 https://github.com/vitejs/docs-cn 与 https://github.com/vuejs-translations/docs-zh-cn 项目的许可证 License 为 `BY-NC-SA` 或 `BY-NC-ND`。

## 链接
- https://en.wikipedia.org/wiki/Creative_Commons_license

**Comment by ShenQingchuan** [comment]
cc @yyx990803 
我也觉得改成这 CC 协议比较好

**Comment by yyx990803** [comment]
同意，改成 BY-NC-SA 好了
