### ISSUE TITLE
这是啥？单纯疑惑

### ISSUE THREAD

**Issue by cloudmoonocus** [vitejs/docs-cn#746]
![image](https://user-images.githubusercontent.com/98140702/229406181-5ec7bdcf-093d-45ac-bb09-f48c5c6ccc23.png)

**Comment by ShenQingchuan** [comment]
@cloudmoonocus 你好，你所访问的应该不是 Vite 官方的中文文档。

请认准链接 URL：https://cn.vitejs.dev

其他网站均为非官方部署。

**Comment by cloudmoonocus** [comment]
好的好的，感谢
