### ISSUE TITLE
【寻人】翻译文档认领 —— 请在本仓库曾经贡献过代码的同学认领文档

### ISSUE THREAD

**Issue by Ivocin** [vitejs/docs-cn#77]
本项目由 @ShenQingchuan 同学牵头从 2021 年 2 月 5 日开始对[官方文档 ](https://github.com/vitejs/vite/tree/main/docs) 进行翻译工作，感谢 @ShenQingchuan 做出的巨大贡献，期间有 23 位同学先后对本仓库进行了贡献。
感谢 @QC-L 和 印记中文 @docschina-bot 帮忙将本项目同步模式从人工同步模式迁移到了自动化模式，详见 #51 
2021-04-01 -  2021-04-05 完成了这项工作，非常感谢。

这次 PR 后，原有的 `main` 主干重命名为 `history`，由于 GitHub Repo 展示的 Contributors 是主干的 Contributors，**导致过去在本仓库贡献过代码的同学从 Contributor 中消失了**，目前的 Contributors 是这样的：

<img width="340" alt="截屏2021-04-13 上午3 57 43" src="https://user-images.githubusercontent.com/16836801/114458495-da8d4300-9c11-11eb-8a40-db26e08eea07.png">

<img width="920" alt="iShot2021-04-13 04 37 30" src="https://user-images.githubusercontent.com/16836801/114458621-00b2e300-9c12-11eb-9888-bff44cd834f3.png">

**这样名字从 Contributors 中消失可能会给很多曾经贡献的同学造成心理伤害，故希望基于 `sync-docs` 分支拉一个新分支，各位曾经的 Contributors 认领部分文档，进行 PR，尽量保证名字回归到 Contributors 中。**

附： Contributors （按照时间排序），如有遗留，请补充

- [旧巷馆子 · 沈青川](https://github.com/ShenQingchuan)
- [beetaa](https://github.com/beetaa)
- [Stephen](https://github.com/shyser)
- [iMaeGoo](https://github.com/imaegoo)
- [hezf](https://github.com/hezhongfeng)
- [KnowsCount](https://github.com/KnowsCount)
- [Suyan](https://github.com/suyanhanx)
- [Caper](https://github.com/caperso)
- [炽翎](https://github.com/wjq990112)
- [luwuer](https://github.com/luwuer)
- [Jingsong Gao](https://github.com/kagawagao)
- [Nyakku Shigure](https://github.com/SigureMo )
- [AtomLiu](https://github.com/G233)
- [清秋](https://github.com/Ivocin)
- [Mr.zhang](https://github.com/zhanglolo)
- [Yang Mingshan](https://github.com/yangmingshan)
- [Zeb Wu](https://github.com/Wzb3422)
- [云深](https://github.com/theprimone)
- [okbug](https://github.com/okbug)
- [sugar](https://github.com/ATQQ)
- [iron](https://github.com/heng1025)
- [QiChang Li](https://github.com/QC-L)

**Comment by Ivocin** [comment]
@ShenQingchuan @QC-L  还请新建分支，请帮忙分配权限

**Comment by QC-L** [comment]
新建过了，和上次一样 dev 分支。

**Comment by Ivocin** [comment]
> 新建过了，和上次一样 dev 分支。

好的，大家认领一下吧
