### ISSUE TITLE
拉取项目，本地运行，safari报错，firefox正常启动

### ISSUE THREAD

**Issue by zhanglolo** [vitejs/docs-cn#8]
safari控制台报错：SyntaxError: Unexpected token ','. Expected a ';' following a targeted export declaration.

![截屏2021-02-07 上午11 05 26](https://user-images.githubusercontent.com/27875371/107135296-7f4e8400-6934-11eb-93b4-c27baf7fc3ce.jpg)

**Comment by KnowsCount** [comment]
我这里没有这样的问题。

不过，在本地 `yarn dev` 的时候出现了这样的问题：

![](https://knowscount-1304485449.cos.ap-shanghai.myqcloud.com/img/Screenshot%202021-02-08%20at%2014.34.53.png)

我笔记本本地是英文环境，可能是这个原因？

**Comment by sodatea** [comment]
参见 https://github.com/vuejs/vitepress/pull/227

**Comment by ShenQingchuan** [comment]
closes #10 due to similarity.

**Comment by sodatea** [comment]
vitepress 0.12 修复了这个问题，需要更新一下依赖。

**Comment by zhanglolo** [comment]
> vitepress 0.12 修复了这个问题，需要更新一下依赖。

👌我试一下

**Comment by zhanglolo** [comment]
更新vitepress至0.12.2后，yarn dev 在safari浏览器中不再报错。👏
