### ISSUE TITLE
vite 怎么再react 中用less的 css module？并且把 xxx.module.less,中的.module文件名去掉，直接xxx.less识别

### ISSUE THREAD

**Issue by Design-duke** [vitejs/docs-cn#813]

**Comment by waynzh** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**，**请不要在此提交关于 Vite 使用的问题或报 Bug**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
