### ISSUE TITLE
打包的时候能排除指定的文件或者文件夹吗 

### ISSUE THREAD

**Issue by caoguizhu** [vitejs/docs-cn#820]

**Comment by ShenQingchuan** [comment]
# Vite 使用问题相关 issue 统一处理
首先感谢你对 Vite 的支持，但这里是 **Vite 官方中文文档的翻译项目相关 issue 的提交站**，**请不要在此提交关于 Vite 使用的问题或报 Bug。**，请移步 [Vite 主仓库 issue 区](https://github.com/vitejs/vite/issues)。

感谢你的配合。
