### ISSUE TITLE
【dev】i got an 404 errors that main.ts is not found but i was  not found in the source 

### ISSUE THREAD

**Issue by Henrycheheng** [vitejs/docs-cn#849]
I got the source code and pnpm run dev script,then i got an error like this:
![image](https://github.com/vitejs/docs-cn/assets/48849602/ec6436dc-5418-46e2-8d57-2ccd9fc55d6c)
so i add "type": "module",as follows picture:
![image](https://github.com/vitejs/docs-cn/assets/48849602/6f20cc85-7d8b-4dc2-91bc-efec7ec1f5a4)
then pnpm run dev got this:
![image](https://github.com/vitejs/docs-cn/assets/48849602/0ef94833-36fa-46b0-a9ce-5f3bf905dedc)
 i was not found 'main.ts' file in the source, anyone can help me to dev  the pro? i had completed to an article translation and wanna to see the effect.

**Comment by ShenQingchuan** [comment]
What's your node.js version?

**Comment by Henrycheheng** [comment]
![image](https://github.com/vitejs/docs-cn/assets/48849602/71567bb0-d891-4b60-a3c3-bc8a98e95d46)
and i use a vsc plugin vitePress and package.json file add "type": "module",then dev server is okay. i'm  not sure that's a problem.

**Comment by ShenQingchuan** [comment]
Thanks for your report, fixed in https://github.com/vitejs/docs-cn/commit/f5d5411a9bef46195016f76543d119d1ff88c2b3
