### ISSUE TITLE
错别字-> 指引->功能->NPM 依赖解析和预构建 -> 依赖是强缓存的 -> 晴->请

### ISSUE THREAD

**Issue by xxGw1997** [vitejs/docs-cn#9]
![lALPDgtYwCkcmuLNAVXNBkc_1607_341](https://user-images.githubusercontent.com/42484647/107171108-ecc5e780-69fc-11eb-8258-fa8cc93dec0d.png)

**Comment by ShenQingchuan** [comment]
Thanks for the issue.
