### ISSUE TITLE
官方插件标题跳转链接404

### ISSUE THREAD

**Issue by luchaoet** [vitejs/docs-cn#920]
插件 -> 官方插件 -> 官方插件的标题链接错误，插件github地址变动，当前地址404

**Comment by waynzh** [comment]
能否提供下具体的链接或者截图呢，试了下没有复现。
https://cn.vitejs.dev/plugins/#official-plugins

**Comment by luchaoet** [comment]
https://www.vitejs.net/plugins/

**Comment by waynzh** [comment]
@luchaoet 你所访问的链接不是 Vite 官方的中文文档。
请认准链接 URL：https://cn.vitejs.dev/ 。其他网站均为非官方部署。
